<?php

declare(strict_types=1);

namespace FelixNagel\T3extblog\Tests\Functional\Controller;

/*
 * This file is part of the "t3extblog" Extension for TYPO3 CMS.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 */

use FelixNagel\T3extblog\Tests\Functional\AbstractFunctionalTestCase;
use TYPO3\CMS\Extbase\Mvc\Controller\MvcPropertyMappingConfigurationService;

abstract class AbstractControllerTestCase extends AbstractFunctionalTestCase
{
    protected array $pathsToLinkInTestInstance = [
        'typo3conf/ext/t3extblog/Tests/Functional/Fixtures/Configuration/sites' => 'typo3conf/sites',
    ];

    protected array $configurationToUseInTestInstance = [
        'MAIL' => [
            'transport' => 'null',
        ],
        'FE' => [
            'pageNotFoundOnCHashError' => false,
            'cacheHash' => [
                'enforceValidation' => false,
            ],
        ],
    ];

    /**
     * Sets up the frontend root page with TypoScript and adds a direct EXTBASEPLUGIN
     * rendering object for the plugin under test. This bypasses tt_content-based
     * content element dispatch and directly renders the Extbase plugin.
     *
     * @param string $extensionName UpperCamelCase extension name, e.g. 'T3extblog'
     * @param string $pluginName    UpperCamelCase plugin name, e.g. 'Blogsystem'
     */
    protected function setUpFrontendWithTypoScript(
        int $pageId = 1,
        string $extensionName = 'T3extblog',
        string $pluginName = 'Blogsystem'
    ): void {
        $this->setUpFrontendRootPage(
            $pageId,
            [
                'constants' => [
                    'EXT:t3extblog/Configuration/TypoScript/constants.typoscript',
                ],
                'setup' => [
                    'EXT:t3extblog/Configuration/TypoScript/setup.typoscript',
                    'EXT:t3extblog/Tests/Functional/Fixtures/Configuration/Page.typoscript',
                ],
            ]
        );
        // Directly render the Extbase plugin without going through tt_content records.
        // This avoids the need for fluid_styled_content's lib.contentElement and the
        // CONTENT/CASE dispatch setup.
        $this->addTypoScriptToTemplateRecord(
            $pageId,
            "page.10 = EXTBASEPLUGIN\npage.10 {\n    extensionName = {$extensionName}\n    pluginName = {$pluginName}\n}"
        );
    }

    /**
     * Generates the Extbase __trustedProperties HMAC token for a set of form fields.
     * Use this when submitting POST forms in tests to bypass Extbase's property mapping
     * security check that normally requires the token generated by <f:form>.
     *
     * @param string   $pluginNamespace  e.g. 'tx_t3extblog_blogsystem'
     * @param string[] $formFieldNames   Fully qualified field names, e.g. ['tx_...[post]', 'tx_...[newComment][author]']
     */
    protected function buildTrustedPropertiesToken(string $pluginNamespace, array $formFieldNames): string
    {
        return $this->get(MvcPropertyMappingConfigurationService::class)
            ->generateTrustedPropertiesToken($formFieldNames, $pluginNamespace);
    }
}
