name: Tests

on:
  push:
    branches-ignore:
      - 'l10n_master'
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        php-versions: [8.2, 8.3]
        typo3-versions: [13.4]

    name: Run tests with PHP ${{ matrix.php-versions }} using TYPO3 ${{ matrix.typo3-versions }}
    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl, mbstring, pdo_sqlite

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php-versions }}-typo3-${{ matrix.typo3-versions }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-versions }}-typo3-${{ matrix.typo3-versions }}-composer-
            ${{ runner.os }}-php-${{ matrix.php-versions }}-typo3-${{ matrix.typo3-versions }}-
            ${{ runner.os }}-php-${{ matrix.php-versions }}-typo3-
            ${{ runner.os }}-php-${{ matrix.php-versions }}-
            ${{ runner.os }}-php-
            ${{ runner.os }}-

      - name: Install composer dependencies
        run: composer require typo3/cms-core "^${{ matrix.typo3-versions }}" --prefer-dist --no-progress

      - name: Run PHP lint
        run: composer run-script test-php-lint

      - name: Run PHPCS
        run: composer run-script test-php-cs-fixer

      - name: Run PHPMD
        run: composer run-script test-php-md

      - name: Run TypoScript linter
        run: composer run-script test-typoscript-lint
